# Generated by Django 2.2.6 on 2019-12-28 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0009_shippingmethods'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shippingmethods',
            options={'verbose_name': 'Opção de Entrega', 'verbose_name_plural': 'Opções de Entrega'},
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_methods',
            field=models.ForeignKey(on_delete='CASCADE', to='checkout.ShippingMethods', verbose_name='Opção de Entrega'),
        ),
    ]
