# Generated by Django 2.2.6 on 2019-12-30 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0010_auto_20191228_1835'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentMethods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_option', models.CharField(choices=[('deposit', 'Depósito'), ('', 'PagSeguro'), ('paypal', 'Paypal'), ('pagamento_entrega', 'Pagamento na Entrega')], default='deposit', max_length=20, verbose_name='Opção de Pagamento')),
            ],
        ),
        migrations.RenameField(
            model_name='order',
            old_name='shipping_methods',
            new_name='shipping_method',
        ),
        migrations.RemoveField(
            model_name='order',
            name='status',
        ),
        migrations.AddField(
            model_name='order',
            name='payment_status',
            field=models.IntegerField(blank=True, choices=[(0, 'Aguardando Pagamento'), (1, 'Concluída'), (2, 'Cancelada')], default=0, verbose_name='Situação do Pagamento'),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_status',
            field=models.IntegerField(blank=True, choices=[(0, 'Aguardando Entrega'), (2, 'Concluída')], default=0, verbose_name='Situação da Entrega'),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_option',
            field=models.ForeignKey(on_delete='CASCADE', to='checkout.PaymentMethods', verbose_name='Opção de Pagamento'),
        ),
    ]
