# Generated by Django 2.2.6 on 2019-12-31 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0011_auto_20191230_1450'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shippingmethods',
            name='name',
            field=models.CharField(choices=[('delivery_by_correios', 'Entrega via Correios'), ('store_pickup', 'Retirada na Loja'), ('fixed_price', 'Entrega com Preço Fixo')], default='delivery_by_correios', max_length=30, unique=True, verbose_name='Opção de Entrega'),
        ),
    ]
