# Generated by Django 2.2.6 on 2020-01-03 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0012_auto_20191231_1103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='shipping_method',
            field=models.CharField(max_length=30, verbose_name='Forma de Entrega'),
        ),
        migrations.DeleteModel(
            name='ShippingMethods',
        ),
    ]
