# Generated by Django 2.2.6 on 2020-01-11 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0013_auto_20200103_1053'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='weight',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Peso'),
        ),
    ]
