# Generated by Django 2.2.6 on 2020-01-11 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0014_cartitem_weight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_option',
            field=models.ForeignKey(null=True, on_delete='CASCADE', to='checkout.PaymentMethods', verbose_name='Opção de Pagamento'),
        ),
    ]
