# Generated by Django 2.2.6 on 2020-01-11 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0015_auto_20200111_1754'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='shipping_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Frete'),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_pickup_day',
            field=models.CharField(blank=True, max_length=30, verbose_name='Dia de Retirada'),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_time',
            field=models.IntegerField(default=0, verbose_name='Tempo de Entrega'),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_tracking_code',
            field=models.CharField(blank=True, max_length=30, verbose_name='Código de Rastreamento'),
        ),
    ]
