# Generated by Django 2.2.6 on 2020-01-13 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0016_auto_20200111_2009'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='weight',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Peso'),
        ),
        migrations.AlterField(
            model_name='order',
            name='shipping_method',
            field=models.CharField(choices=[('none', 'Escolha a Forma de Entrega'), ('delivery_by_correios_sedex', 'Entrega via Correios SEDEX'), ('delivery_by_correios_pac', 'Entrega via Correios PAC'), ('store_pickup', 'Retirada na Loja')], max_length=30, verbose_name='Forma de Entrega'),
        ),
    ]
