# Generated by Django 2.2.6 on 2020-01-16 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0019_auto_20200116_1126'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paymentmethods',
            options={'verbose_name': 'Método de Pagamento', 'verbose_name_plural': 'Métodos de Pagamento'},
        ),
        migrations.AddField(
            model_name='order',
            name='order_details',
            field=models.TextField(blank=True, max_length=255, verbose_name='Detalhes do Pedido'),
        ),
    ]
