# Generated by Django 2.2.6 on 2020-01-16 20:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0020_auto_20200116_1141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentmethods',
            name='order',
            field=models.OneToOneField(default=107, on_delete=django.db.models.deletion.CASCADE, related_name='payment_method', to='checkout.Order', verbose_name='Pedido'),
        ),
    ]
