# Generated by Django 2.2.6 on 2020-01-17 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0021_auto_20200116_1717'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='shipping_status',
            field=models.IntegerField(blank=True, choices=[(0, 'Aguardando Entrega'), (1, 'Aguardando Retirada'), (2, 'Concluída')], default=0, verbose_name='Situação da Entrega'),
        ),
        migrations.AlterField(
            model_name='paymentmethods',
            name='payment_option',
            field=models.CharField(choices=[('deposit', 'Depósito'), ('pagseguro', 'PagSeguro'), ('payment_on_delivery_cash', 'Pagamento na Entrega em Dinheiro')], default='deposit', max_length=100, verbose_name='Opção de Pagamento'),
        ),
    ]
