# Generated by Django 2.2.6 on 2020-01-18 17:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0022_auto_20200117_1511'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentmethods',
            name='order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment_method', to='checkout.Order', verbose_name='Pedido'),
        ),
        migrations.AlterField(
            model_name='paymentmethods',
            name='payment_option',
            field=models.CharField(choices=[('deposit', 'Depósito'), ('pagseguro', 'PagSeguro')], default='deposit', max_length=100, verbose_name='Opção de Pagamento'),
        ),
    ]
