# Generated by Django 2.2.6 on 2020-01-18 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0023_auto_20200118_1448'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentmethods',
            name='payment_option',
            field=models.CharField(max_length=100, verbose_name='Opção de Pagamento'),
        ),
    ]
