# Generated by Django 2.2.6 on 2020-01-23 01:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0024_auto_20200118_1558'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='payment_status',
        ),
        migrations.RemoveField(
            model_name='order',
            name='shipping_cost',
        ),
        migrations.RemoveField(
            model_name='order',
            name='shipping_method',
        ),
        migrations.RemoveField(
            model_name='order',
            name='shipping_pickup_day',
        ),
        migrations.RemoveField(
            model_name='order',
            name='shipping_status',
        ),
        migrations.RemoveField(
            model_name='order',
            name='shipping_time',
        ),
        migrations.RemoveField(
            model_name='order',
            name='shipping_tracking_code',
        ),
        migrations.AddField(
            model_name='cartitem',
            name='status',
            field=models.IntegerField(blank=True, choices=[(0, 'Aberto'), (1, 'Concluído'), (2, 'Abandonado')], default=0, verbose_name='Situação do Cesta'),
        ),
        migrations.AddField(
            model_name='order',
            name='order_status',
            field=models.IntegerField(blank=True, choices=[(0, 'Aberto'), (1, 'Concluído'), (2, 'Abandonado')], default=0, verbose_name='Situação do Pedido'),
        ),
        migrations.AddField(
            model_name='paymentmethods',
            name='payment_status',
            field=models.IntegerField(blank=True, choices=[(0, 'Aguardando Pagamento'), (1, 'Concluída'), (2, 'Cancelada')], default=0, verbose_name='Situação do Pagamento'),
        ),
        migrations.AlterField(
            model_name='paymentmethods',
            name='payment_option',
            field=models.CharField(blank=True, default='deposit', max_length=100, verbose_name='Opção de Pagamento'),
        ),
        migrations.CreateModel(
            name='ShippingMethods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shipping_status', models.IntegerField(blank=True, choices=[(0, 'Aguardando Entrega'), (1, 'Aguardando Retirada'), (2, 'Concluída')], default=0, verbose_name='Situação da Entrega')),
                ('shipping_method', models.CharField(choices=[('none', 'Escolha a Forma de Entrega'), ('delivery_by_correios_sedex', 'Entrega via Correios SEDEX'), ('delivery_by_correios_pac', 'Entrega via Correios PAC'), ('store_pickup', 'Retirada na Loja')], max_length=30, verbose_name='Forma de Entrega')),
                ('shipping_pickup_day', models.CharField(blank=True, max_length=30, verbose_name='Dia de Retirada')),
                ('shipping_cost', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Frete')),
                ('shipping_time', models.IntegerField(default=0, verbose_name='Tempo de Entrega')),
                ('shipping_tracking_code', models.CharField(blank=True, max_length=30, verbose_name='Código de Rastreamento')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='shipping_method', to='checkout.Order', verbose_name='Pedido')),
            ],
            options={
                'verbose_name': 'Forma de Entrega',
                'verbose_name_plural': 'Formas de Entrega',
            },
        ),
    ]
