# Generated by Django 2.2.6 on 2020-01-24 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0025_auto_20200122_2230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shippingmethods',
            name='shipping_method',
            field=models.CharField(choices=[('None', 'Escolha a Forma de Entrega'), ('sedex', 'Entrega via Correios SEDEX'), ('pac', 'Entrega via Correios PAC'), ('store_pickup', 'Retirada na Loja')], max_length=30, verbose_name='Forma de Entrega'),
        ),
        migrations.AlterField(
            model_name='shippingmethods',
            name='shipping_pickup_day',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Dia de Retirada'),
        ),
    ]
