# Generated by Django 2.2.6 on 2019-12-25 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20191112_1041'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile',
            field=models.CharField(choices=[('Customer', 'Customer'), ('Vendor', 'Vendor'), ('Administrator', 'Administrator')], default='Customer', max_length=100, verbose_name='Perfil'),
        ),
    ]
