# Generated by Django 2.2.6 on 2019-12-25 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraddress',
            name='is_billing_address',
            field=models.BooleanField(default=True, verbose_name='Endereço de Cobrança'),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile',
            field=models.CharField(choices=[('Customer', 'Cliente'), ('Vendor', 'Vendedor'), ('Administrator', 'Administrador')], default='Customer', max_length=100, verbose_name='Perfil'),
        ),
    ]
