# Generated by Django 2.2.6 on 2019-10-27 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete='SET_NULL', to='catalog.Category', verbose_name='Categoria'),
        ),
    ]
