# Generated by Django 2.2.6 on 2019-10-30 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_auto_20191030_1831'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete='SET_NULL', to='catalog.Category', verbose_name='Categoria'),
        ),
    ]
