# Generated by Django 2.2.6 on 2019-11-15 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_product_short_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='short_description',
            field=models.TextField(blank=True, max_length=255, verbose_name='Descrição Curta'),
        ),
    ]
